pg4_Company/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Project_TFM10304.Attributes;
using Project_TFM10304.Data;
using Project_TFM10304.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;

namespace Project_TFM10304.Controllers
{
    //權限 & layout設定
    [ViewLayout("_CompanyLayout")]
    [Authorize(Roles = "Company")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<Users> _userManager;

        public OrderController(ApplicationDbContext dbContext,
            UserManager<Users> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        //歷史訂單
        public IActionResult Index()
        {
            return View();
        }

        //歷史訂單 初始資料
        public string MyOrders()
        {
            ClaimsPrincipal thisUser = this.User;
            var IsCompany = thisUser.IsInRole("Company");

            if (IsCompany == true)
            {
                var userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

                //join [order, orderDetail, Product], groupby(product.name), 將orderDetail.quantity加總
                var ordersGroups = _dbContext.Order
                    .Join(_dbContext.OrderDetail, o => o.OrderId, od => od.OrderId, (o, od) =>
                    new
                    {
                        id = o.OrderId,
                        productId = od.ProductId,
                        quantity = od.Quantity,
                    })
                    .Join(_dbContext.Product, od => od.productId, p => p.Id, (od, p) =>
                    new
                    {
                        oid = od.id,
                        productName = p.Name,
                        price = p.Price,
                        quantity = od.quantity,
                        psdate = p.StartDate,
                        pedate = p.EndDate,
                        cid = p.CompanyUserId
                    })
                    .Where(o => o.cid == userId && o.pedate <= DateTime.Now).Select(r =>
                    new {
                        oid = r.oid,
                        productName = r.productName,
                        price = r.price,
                        quantity = r.quantity,
                        psdate = r.psdate.ToString("yyyy/MM/dd"),
                        pedate = r.pedate.ToString("yyyy/MM/dd"),
                        totalPrice = r.price * r.quantity
                    });

                var jsonResult = JsonSerializer.Serialize(ordersGroups);
                return jsonResult;
            }
            return "";
        }

        public string GetOrders(string sdate, string edate)
        {
            ClaimsPrincipal thisUser = this.User;
            string userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            DateTime dts = (sdate == null) ? DateTime.Parse("2000-01-01") : DateTime.Parse(sdate);
            DateTime dte = (edate == null) ? DateTime.Now : DateTime.Parse(edate);

            var query = _dbContext.Order.Join(_dbContext.OrderDetail, o => o.OrderId, od => od.OrderId, (o, od) => new { id = o.OrderId, pid = od.ProductId, qty = od.Quantity })
                .Join(_dbContext.Product, o => o.pid, p => p.Id, (o, p) => new { cid = p.CompanyUserId, oid = o.id, productName = p.Name, price = p.Price, quantity = o.qty, psdate = p.StartDate, pedate = p.EndDate })
                .Where(o => o.cid == userId && o.psdate >= dts && o.pedate <= dte)
                .Select(r => new { oid = r.oid, productName = r.productName, price = r.price, quantity = r.quantity, psdate = r.psdate.ToString("yyyy/MM/dd"), pedate = r.pedate.ToString("yyyy/MM/dd"), totalPrice = r.price * r.quantity });

            return JsonSerializer.Serialize(query);
        }

        //初始化Demo用的資料
        public void DemoInit()
        {
            ClaimsPrincipal thisUser = this.User;
            string userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            Product p1 = new() { CompanyUserId = userId, Name = "第一期 | 金工體驗初階班", Price = 1000, StartDate = DateTime.Parse("2022-01-09").AddHours(13).AddMinutes(30), EndDate = DateTime.Parse("2022-01-09").AddHours(15).AddMinutes(30) };
            Product p2 = new() { CompanyUserId = userId, Name = "第二期 | 金工體驗初階班", Price = 1000, StartDate = DateTime.Parse("2022-01-16").AddHours(13).AddMinutes(30), EndDate = DateTime.Parse("2022-01-16").AddHours(15).AddMinutes(30) };
            Product p3 = new() { CompanyUserId = userId, Name = "第三期 | 金工體驗初階班", Price = 1000, StartDate = DateTime.Parse("2022-01-23").AddHours(13).AddMinutes(30), EndDate = DateTime.Parse("2022-01-23").AddHours(15).AddMinutes(30) };
            Product p4 = new() { CompanyUserId = userId, Name = "第一期 | 金工進階探索班", Price = 2999, StartDate = DateTime.Parse("2022-01-22").AddHours(13).AddMinutes(30), EndDate = DateTime.Parse("2022-01-22").AddHours(18).AddMinutes(30) };

            _dbContext.Product.AddRange(p1, p2, p3, p4);
            _dbContext.SaveChanges();

            Order o1 = new() { OrderId = "O20220105001", UserId = userId };
            Order o2 = new() { OrderId = "O20220105002", UserId = userId };

            Order o3 = new() { OrderId = "O20220113001", UserId = userId };
            Order o4 = new() { OrderId = "O20220114001", UserId = userId };

            Order o5 = new() { OrderId = "O20220120001", UserId = userId };
            Order o6 = new() { OrderId = "O20220121001", UserId = userId };

            _dbContext.Order.AddRange(o1, o2, o3, o4, o5, o6);
            _dbContext.SaveChanges();

            //p6: 9筆總售出
            OrderDetail od1 = new() { OrderId = "O20220105001", ProductId = p1.Id, Quantity = 4 };
            OrderDetail od2 = new() { OrderId = "O20220105002", ProductId = p1.Id, Quantity = 5 };

            OrderDetail od3 = new() { OrderId = "O20220113001", ProductId = p2.Id, Quantity = 6 };
            OrderDetail od4 = new() { OrderId = "O20220114001", ProductId = p2.Id, Quantity = 6 };

            OrderDetail od5 = new() { OrderId = "O20220120001", ProductId = p3.Id, Quantity = 6 };
            OrderDetail od6 = new() { OrderId = "O20220114001", ProductId = p4.Id, Quantity = 6 };

            _dbContext.AddRange(od1, od2, od3, od4, od5, od6);
            _dbContext.SaveChanges();
        }
    }
}

pg4_Company/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using pg4_Company.ViewModels;
using Project_TFM10304.Attributes;
using Project_TFM10304.Data;
using Project_TFM10304.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;

namespace pg4_Company.Controllers
{
    //權限 & layout設定
    [ViewLayout("_CompanyLayout")]
    [Authorize(Roles = "Company")]
    public class ProductController : Controller
    {
        private readonly IWebHostEnvironment env;
        private readonly ApplicationDbContext db;
        private readonly string fileroot = @"\pic\product\";
        public ProductController(IWebHostEnvironment env, ApplicationDbContext db)
        {
            this.env = env;
            this.db = db;
        }

        //商品首頁, 顯示目前使用者的商品
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MyProducts()  //商品管理
        {
            return View("Index");
        }
        public IActionResult ProductSource() //api傳回Product值: 已上架
        {
            ClaimsPrincipal thisUser = this.User;
            var userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            var query = db.Product.Where(p=>p.IsSold == true && p.CompanyUserId == userId).Select(p => new
            { ProductPic = p.ProductPic.FirstOrDefault(), p.Price, p.Id, p.Name, p.StartDate, p.EndDate, p.IsSold });
            var on = query.Where(p => p.IsSold == true);
            return Json(on);
        }

        public IActionResult ProductSourceOff() //api傳回Product值: 未上架
        {
            ClaimsPrincipal thisUser = this.User;
            var userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            var query = db.Product.Where(p=>p.IsSold == false && p.CompanyUserId == userId).Select(p => new
            { ProductPic = p.ProductPic.FirstOrDefault(), p.Price, p.Id, p.Name, p.StartDate, p.EndDate, p.IsSold });
            var off = query.Where(p => p.IsSold == false);
            return Json(off);
        }

        //於Index下架商品
        [HttpPost]
        public IActionResult DeletePd([FromForm] int id)
        {
            List<Product> pd = db.Product.ToList();
            var p = pd.FirstOrDefault(p => p.Id == id);

            p.IsSold = false;
            db.SaveChanges();

            return Ok();
        }

        //於Index上架商品
        public IActionResult OnPd(int id)
        {
            List<Product> pd = db.Product.ToList();
            var p = pd.FirstOrDefault(p => p.Id == id);

            p.IsSold = true;
            db.SaveChanges();

            return Ok();
        }

        //新增商品
        public IActionResult Create()
        {
            return View();
        }

        //接收新增商品表單, 處理圖片上傳
        [HttpPost]
        public IActionResult Upload(CreateProductViewModel data)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                return Ok($"發生錯誤: {errors}");
            }

            ClaimsPrincipal thisUser = this.User;
            var userId = thisUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            //新增至Product Table
            Product p = new Product();
            p.CompanyUserId = userId;
            p.Name = data.Name;
            p.Price = data.Price;
            p.Type = data.Type;
            p.TotalStock = data.TotalStock;
            p.StockForSale = data.TotalStock;
            p.Location = data.Location;
            p.Description_S = data.Description_S;
            p.Description_L = data.Description_L;
            p.Description_L_1 = data.Description_L_1;
            p.Description_L_2 = data.Description_L_2;
            p.Description_L_3 = data.Description_L_3;
            p.Description_L_4 = data.Description_L_4;
            p.Description_L_5 = data.Description_L_5;
            p.StartDate = data.StartDate;
            p.EndDate = data.EndDate;
            p.IsSold = data.IsSold;
            db.Product.Add(p);
            db.SaveChanges();

            var basePath = $@"{env.WebRootPath}";

            if (data.Pic != null)  //有傳圖片
            {
                //逐筆新增ProductPic
                foreach (var f in data.Pic)
                {
                    var combinFileName = $@"{fileroot}{p.Id}_{f.FileName}"; //宣告每次檔案路徑+名稱
                    using (var fileSteam = System.IO.File.Create($@"{basePath}{combinFileName}"))
                    {
                        f.CopyTo(fileSteam);
                    }

                    db.ProductPic.Add(new ProductPic
                    {
                        ProductId = p.Id,
                        PicPath = $"/pic/product/{p.Id}_{f.FileName}"
                    });
                    db.SaveChanges();
                }
            }
            return RedirectToAction("MyProducts");
        }//upload

        //編輯商品
        public IActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetPdSession( int id)    //於Index按下編輯 > 傳回該ProductId 並存到Session
        {
            HttpContext.Session.SetInt32("ProductId", id);      //(key , value)
            return Json(id);
        }

        //Edit 取得初始資料
        public IActionResult GetPdSession()                                   //API      Get Session的ProductId傳出去
        {
            List<Product> pd = db.Product.ToList();
            var id = HttpContext.Session.GetInt32("ProductId");

            var totalSale = db.OrderDetail.Where(o => o.ProductId == id).Select(o => o.Quantity).Sum(); //已銷售的數量
            var data = (pd.Where(x => x.Id == id)).Select(p => new { p.Name, p.Price, p.Location, p.TotalStock, stockForSale = (p.TotalStock - totalSale), p.Description_S, p.Description_L, p.Description_L_1, p.Description_L_2, p.Description_L_3, p.Description_L_4, p.Description_L_5, p.StartDate, p.EndDate, p.IsSold,p.Type });

            //var data = (pd.Where(x => x.Id == id));
            return Json(data);
        }

        //Edit 取得初始資料 商品圖片
        public IActionResult GetPic()
        {
            List<ProductPic> pic = db.ProductPic.ToList();
            var id = HttpContext.Session.GetInt32("ProductId");

            var data = (pic.Where(pic => pic.ProductId == id));
            return Json(data);
        }

        //刪除圖片
        [HttpPost]
        public IActionResult DeletePic([FromForm] int id)
        {
            List<ProductPic> pic = db.ProductPic.ToList();
            var pp = pic.FirstOrDefault(p => p.Id == id);
            db.ProductPic.Remove(pp);
            db.SaveChanges();
            return Json(pp);
        }

        [HttpPost]
        public IActionResult UpdatePic(EditProductPicViewModel data) //更新圖片
        {
            var PdId = HttpContext.Session.GetInt32("ProductId");
            var basePath = $@"{env.WebRootPath}";

            if (data != null)
            {
                var pic = $@"{data.UpPic.FileName}";

                var combinFileName = $@"{fileroot}{PdId}_{data.UpPic.FileName}"; //宣告每次檔案路徑+名稱
                using (var fileSteam = System.IO.File.Create($@"{basePath}{combinFileName}"))
                {
                    data.UpPic.CopyTo(fileSteam);
                }
                HttpContext.Session.SetString("PicPath", $@"{PdId}_{data.UpPic.FileName}");

            }

            return Ok();
        }

        [HttpPost]
        public IActionResult CheckUpdatePic([FromForm] int id)
        {
            var path = HttpContext.Session.GetString("PicPath");

            List<ProductPic> pic = db.ProductPic.ToList();

            var P = pic.FirstOrDefault(p => p.Id == id);
            P.PicPath = $"/pic/product/{path}";
            db.SaveChanges();

            return Json(P);
        }

        //接收Edit送出的表單
        public IActionResult EditUpdate(EditProductViewModel data)  //
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                return Ok($"發生錯誤: {errors}");
            }

            //鎖定欲編輯的product, 更新相關資料
            var id = HttpContext.Session.GetInt32("ProductId");
            var PdDb = db.Product.FirstOrDefault(x => x.Id == id);

            if (id != null)
            {
                PdDb.Name = data.Name;
                PdDb.Price = data.Price;
                PdDb.Type = data.Type;
                PdDb.Location = data.Location;
                PdDb.Description_S = data.Description_S;
                PdDb.Description_L = data.Description_L;
                PdDb.Description_L_1 = data.Description_L_1;
                PdDb.Description_L_2 = data.Description_L_2;
                PdDb.Description_L_3 = data.Description_L_3;
                PdDb.Description_L_4 = data.Description_L_4;
                PdDb.Description_L_5 = data.Description_L_5;
                PdDb.StartDate = data.StartDate;
                PdDb.EndDate = data.EndDate;
                PdDb.IsSold = data.IsSold;

                var basePath = $@"{env.WebRootPath}";

                if (data.Pic != null)  //有傳圖片
                {
                    foreach (var f in data.Pic)
                    {
                        var combinFileName = $@"{fileroot}{id}_{f.FileName}"; //宣告每次檔案路徑+名稱
                        using (var fileSteam = System.IO.File.Create($@"{basePath}{combinFileName}"))
                        {
                            f.CopyTo(fileSteam);
                        }

                        db.ProductPic.Add(new ProductPic
                        {
                            ProductId = PdDb.Id,
                            PicPath = $"/pic/product/{id}_{f.FileName}"
                        });
                        db.SaveChanges();
                    }
                }
                db.SaveChanges();

pg4_Company/Views/Shared/_CompanyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAPAGO | 樂商家</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!----axios-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.24.0/axios.min.js" integrity="sha512-u9akINsQsAkG9xjc1cnGF4zw5TFDwkxuc9vUp5dltDWYCSmyd0meygbvgXrlc/z7/o4a19Fb5V0OUE58J7dcyw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>  <!----Jquery-->

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script> <!----VUE-->

    @*vue-chart.js*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="https://unpkg.com/vue-chartjs/dist/vue-chartjs.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="CompanyHome" asp-action="Index">
                    <img src="~/pic/PAPAGO_logo2-01.png" style="width: 80px;height: 72px;" class="d-inline-block align-top" alt="logo">
                </a>
                <a class="navbar-brand" asp-area="" asp-controller="CompanyHome" asp-action="Index">PAPAGO | 樂商家</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="MyProducts">商品管理</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Order" asp-action="Index">歷史訂單</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="CompanyUser" asp-action="Manage">會員中心</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">回首頁</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Project_TFM10304 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

pg4_Company/Views/Shared/_LoginLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Project_TFM10304.Models.Users> SignInManager
@inject UserManager<Project_TFM10304.Models.Users> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-signin-client_id" content="403118786851-ot5s3leecq2oa6id3psv3vvk3u085dau.apps.googleusercontent.com">
    <title>@ViewData["Title"] - Papago</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/site1.css" rel="stylesheet" />
    <link href="~/css/test.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site2.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.10.1/main.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/moment.js"></script>
</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    {
        <div style="padding-bottom:60px">
            <div style="display:flex; justify-content:space-between; width:100%;height:60px;position:fixed;background-color:white;z-index:99999999;">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/pic/LOGO-01.png" class="index-logo"></a>
                <div style="display:flex;flex-wrap:wrap;align-items:center">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    }
    else
    {

    }


    <div>
        <main style="overflow:hidden">
            @RenderBody()
        </main>
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

pg4_Company/Views/Shared/_ProductLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Project_TFM10304.Models.Users> SignInManager
@inject UserManager<Project_TFM10304.Models.Users> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Papago</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site2.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        Vue.config.devtools = true;
    </script>
    <style>
        /* Dropdown Button */
        .dropbtn {
            color: white;
            font-size: 16px;
            border: none;
        }
        /* The container <div> - needed to position the dropdown content */
        .dropdown {
            position: relative;
            display: inline-block;
        }
        /* Dropdown Content (Hidden by Default) */
        .dropdown-content {
            display: none;
            position: absolute;
            right:0;
            background-color: #f1f1f1;
            min-width: 250px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }


            /* Links inside the dropdown */
            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                /* Change color of dropdown links on hover */
                .dropdown-content a:hover {
                    background-color: #ddd;
                }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }
        /* Change the background color of the dropdown button when the dropdown content is shown */
        .dropdown:hover .dropbtn {
            background-color: #8cc2f5;
        }

        .dropdown-menu-end {
            right: 0;
            left: auto;
        }

        .panel {
            height: 60vh;
        }
    </style>
</head>

<body>
    <div style="padding-bottom:60px">
        <div style="display:flex; justify-content:space-between; width:100%;height:60px;position:fixed;background-color:white;z-index:99999999;">
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/pic/LOGO-01.png" class="index-logo"></a>
            <div style="display:flex;flex-wrap:nowrap;align-items:center">
                <div id="cartMenu">
                    <div class="dropdown">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Cartlist">
                            <img style="width: 32px; height: 32px;align-items:center;" src="~/pic/購物車.png" />
                            <div class="badge bg-info">{{product.length}}</div>
                        </a>

                        <div class="dropdown-content" style="overflow-y:scroll">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a asp-area="" asp-controller="Home" asp-action="Cartlist" class="btn btn-primary">查看購物車</a>
                                </div>
                                <div class=" panel-body ">
                                    <div v-for="p in product" class="card" style="width: 17rem;">
                                        <img :src="p.imagePath" class="card-img-top" alt="">
                                        <div class="card-body">
                                            <h5 class="card-title">{{p.productName}}</h5>
                                            <p class="card-text">{{p.description_S}}</p>
                                            <p class="card-text">{{p.price}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel">
                                    <div class="card-footer">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="nav-item">
                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"><img style="width:30px;" src="~/img/user-circle-solid.png" /></a>
                    </div>
                    <div class="nav-item">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button type="submit" class="nav-link btn btn-link text-dark"><img style="width:30px;" src="~/img/sign-out-alt-solid.png" /></button>
                        </form>
                    </div>
                }
                else
                {
                    <div class="nav-item">
                        <a class="nav-link text-dark" style="font-family: Microsoft YaHei,sans-serif;" asp-area="Identity" asp-page="/Account/Register">注冊</a>
                    </div>
                    <div class="nav-item">
                        <a class="nav-link text-dark" style="font-family: Microsoft YaHei,sans-serif;" asp-area="Identity" asp-page="/Account/UserLogin">登錄</a>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Papago - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site1.js"></script>
    <script>
        $(function () {
            $("#btn1").click(function () {
                $("#btn1").addClass("active");
                $("#btn2").removeClass("active");
                $("#table2").hide();
                $("#table1").show();
            });
            $("#btn2").click(function () {
                $("#btn1").removeClass("active");
                $("#btn2").addClass("active");
                $("#table1").hide();
                $("#table2").show();
            });
        });
        var vcart = new Vue({
            el: '#cartMenu',
            data: {
                product: [],
                count: 3
            },
            mounted: function () {
                this.GetCartProduct();
            },
            methods: {
                GetCartProduct: function () {
                    let self = this;
                    fetch("/tocProduct/GetCart")
                        .then(function (res) { return res.json() })
                        .then(function (d) { self.product = d })
                }
            }
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>